<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
The inputs to the network. This is the layer that takes the features of your dataset into the model. The rest of the model's nodes can be thought of as a function that creates the output node values
### Hidden Layer:
All the layers inbetween the input and output layer. The structure of the hidden layers determines the "Effective function" that the neural network models
### Output Layer:
The Output of the network. The target. The value you guess based on input values
### Neuron:
A single node in a neural network. It has a function that defines how it processes data internally. For a hidden layer this is a combination of a weighted sum and a sigmoid function ( to make sure the influence of any one part of the node graph isn't higher than any other part of the node graph.
### Weight:
A modification of a value based on its importance in the network. Weights are initialized randomly, and then they are tuned in the training process.
### Activation Function:
A function that maps an input value ( often a weighted sum of the previous layer of the neural net ) to an output range between 0 and 1 
### Node Map:
A visual of the structure of the neural network
### Perceptron:
A simple neural network with just one input layer, and one output layer.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Utility functions:

In [200]:
def crprint(arglist):
    """Utility function for printing out series of data
    Input a string of things to print out and it will 
    insert a carriage return (cr) between the objects in the
    list"""
    for i in arglist:
        print(i)

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [114]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

One of the things to watch out for when implimenting perceptrons is array sizes. The issues I've had with implimentation have all involved the wrong sizes for arrays input to the function, or to a step of the process. 


In [302]:
data = np.array([[0,0,1],
        [1,0,1],
        [0,1,1],
        [1,1,1]])
target = np.array([[1],
          [1],
          [1],
          [0]])
crprint(["Data",data.shape,data,"","Target",target.shape,target])

Data
(4, 3)
[[0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 1]]

Target
(4, 1)
[[1]
 [1]
 [1]
 [0]]


In [88]:
# Activation functions
def sigmoid (x):
    return 1/(1+np.exp(-x))
    
def sigmoid_derivative(x):
    dx = sigmoid(x)
    return dx*(1-dx)

In [306]:
np.random.seed(45)
weights = np.random.randn(3).reshape(-1,1) # more generally -1,1 so that it auto detects scale
weights


array([[ 0.02637477],
       [ 0.2603217 ],
       [-0.39514554]])

In [307]:
weights.shape

(3, 1)

In [308]:
print(weights.shape)
weights

(3, 1)


array([[ 0.02637477],
       [ 0.2603217 ],
       [-0.39514554]])

In [309]:
weighted_sum = np.dot(data,weights)
print(weighted_sum.shape)
weighted_sum

(4, 1)


array([[-0.39514554],
       [-0.36877077],
       [-0.13482384],
       [-0.10844907]])

In [310]:
# Activate
activated_output = sigmoid(weighted_sum)
print(activated_output.shape)
activated_output

(4, 1)


array([[0.40247923],
       [0.40883808],
       [0.466345  ],
       [0.47291427]])

In [311]:
print(target.shape)
target

(4, 1)


array([[1],
       [1],
       [1],
       [0]])

In [312]:
# Calc error
error = target - activated_output
print(error.shape)
error

(4, 1)


array([[ 0.59752077],
       [ 0.59116192],
       [ 0.533655  ],
       [-0.47291427]])

In [313]:
adjustments = error * sigmoid_derivative(activated_output)
print(adjustments.shape)
adjustments

(4, 1)


array([[ 0.14349034],
       [ 0.1417828 ],
       [ 0.12641516],
       [-0.11185699]])

In [314]:
print(data.shape)
data

(4, 3)


array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [315]:
# Update the Weights
wt_change = np.dot(data.T,adjustments)
wt_change

array([[0.02992581],
       [0.01455817],
       [0.29983131]])

In [316]:
print(weights.shape)
weights

(3, 1)


array([[ 0.02637477],
       [ 0.2603217 ],
       [-0.39514554]])

In [317]:
weights += wt_change

In [318]:
weights

array([[ 0.05630058],
       [ 0.27487987],
       [-0.09531423]])

## Implimenting code in a loop:

The way that the class for implimenting the perceptron should specify in its documentation how it expects the input. For our implimentation it takes in training data in the form of:

`X = [# observations,# features]` 
and
`y  = [# observations, # outputs]`

In [319]:
crprint([data.shape,target.shape])

(4, 3)
(4, 1)


In [326]:
percept = Perceptron(1000)
percept.fit(data,target)

[[-1.47331424]
 [ 0.8019266 ]
 [-1.75075239]]


In [327]:
percept.predict(data)

Weights after training
(3, 1)
[[-7.1952543 ]
 [-7.19525337]
 [10.84869329]]


array([[0.99998057],
       [0.97475207],
       [0.97475209],
       [0.02814562]])

In [222]:
target

array([[1],
       [1],
       [1],
       [0]])

In [256]:
data

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [330]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()
diabetes['bias_term']=np.ones(len(diabetes))

In [335]:
print(diabetes.shape)
diabetes.head()

(768, 10)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  bias_term  
0                     0.627   50        1        1.0  
1                     0.351   31        0        1.0  
2                     0.672   32        1        1.0  
3                     0.167   21        0        1.0  
4                     2.288   33        1        1.0

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [358]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-2]
feats.append('bias_term')

In [359]:
print(feats)

['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'bias_term']


In [360]:
a = MinMaxScaler()
X = a.fit_transform(diabetes[feats])
scaled_data = pd.DataFrame(b)
# a.transform[]
# X = ...

In [361]:
X.shape

(768, 9)

In [362]:
X.shape[0]

768

In [363]:
scaled_data.head()

0         1         2         3         4         5         6  \
0  0.352941  0.743719  0.590164  0.353535  0.000000  0.500745  0.234415   
1  0.058824  0.427136  0.540984  0.292929  0.000000  0.396423  0.116567   
2  0.470588  0.919598  0.524590  0.000000  0.000000  0.347243  0.253629   
3  0.058824  0.447236  0.540984  0.232323  0.111111  0.418778  0.038002   
4  0.000000  0.688442  0.327869  0.353535  0.198582  0.642325  0.943638   

          7  
0  0.483333  
1  0.166667  
2  0.183333  
3  0.000000  
4  0.200000

In [364]:
y = np.array(diabetes['Outcome']).reshape(-1,1)
y.shape

(768, 1)

In [365]:
percept = Perceptron(10)
percept.fit(X,y)

[[-0.49505193]
 [-1.00860081]
 [ 0.02524419]
 [-0.12150685]
 [-1.54687318]
 [-0.60694397]
 [-1.39381267]
 [-0.62769549]
 [ 0.33263215]]


In [366]:
percept.predict(X)

Weights after training
(9, 1)
[[ -0.63463526]
 [-17.047768  ]
 [-55.32998871]
 [-12.0065494 ]
 [  1.20825584]
 [-27.79746359]
 [ -2.4067352 ]
 [  4.72553927]
 [  0.33263215]]


array([[1.18406513e-27],
       [5.35597038e-23],
       [2.37307593e-24],
       [2.65795163e-23],
       [9.01487013e-24],
       [4.73186304e-24],
       [1.22503578e-20],
       [2.86399368e-11],
       [2.44837865e-28],
       [2.35101319e-23],
       [1.63916016e-29],
       [2.60158077e-28],
       [4.53649082e-26],
       [1.54572568e-24],
       [6.70760750e-26],
       [9.19687216e-10],
       [4.19683719e-32],
       [1.85498723e-24],
       [7.34655354e-20],
       [2.22413469e-26],
       [5.91917329e-32],
       [1.33878761e-26],
       [1.67763769e-32],
       [6.30572032e-28],
       [5.03469773e-32],
       [1.36084438e-25],
       [1.07689704e-27],
       [2.23756802e-22],
       [2.97695077e-26],
       [5.97247151e-29],
       [2.34487829e-26],
       [3.70479474e-29],
       [1.56877540e-20],
       [9.31759723e-26],
       [9.21598327e-27],
       [2.30363854e-22],
       [1.17829564e-26],
       [6.53319930e-27],
       [1.43314749e-26],
       [1.63578270e-27],


In [321]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def sigmoid(self, x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self, x):
        dx = self.sigmoid(x)
        return dx*(1-dx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        # Randomly Initialize Weight
        # this is with the assumption that the perceptron
        # had two input neurons.
        
        # Initialize n variables reshaped to -1,1 (column vector) 
        num_weights = X.shape[1]
        weights = np.random.randn(num_weights).reshape(-1,1)
        print(weights)
        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X,weights)
            # Activate!
            activated_output = self.sigmoid(weighted_sum)
#             print('Activated output',activated_output)
            # Calc error
            error = y - activated_output
#             print("Error",error)
            adjustments = error * self.sigmoid_derivative(activated_output)
            # Update the Weights
            weights += np.dot(X.T,adjustments)
#             print("Weights",weights)
        self.weights = weights

    def predict(self, X):
        """Return class label after unit step"""
        print("Weights after training")
        crprint([self.weights.shape,self.weights])
        return self.sigmoid(np.dot(X,self.weights))

In [15]:
import numpy as np
weights = np.random.randn(2)
X = [1,1]
np.dot(X,weights)

-0.7964161310180322

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?